#!/usr/bin/env bash
# Installs nginx on a web server and add a redirect
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx start
sudo sed -i "/^\tlocation \// i\ \tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=HPk-VhRjNI8&list=PL3KnTfyhrIlcudeMemKd6rZFGDWyK23vx&index=1;\n\t}" /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx reload
