#!/usr/bin/env bash
# Installs formats a server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" > /var/www/html/index.html
sudo sed -i '/^\tserver_name.*/a \\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' 
sudo service nginx start
