#!/usr/bin/env bash
# Installs formats a load balancer
sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
echo -e 'ENABLED=1' | sudo tee -a /etc/default/haproxy
echo -e 'frontend http-in
\tmode http
\tbind *:80
\tdefault_backend web_servers
backend web_servers
\tbalance roundrobin
\tserver 1886-web-01 34.75.117.102:80 check
\tserver 1886-web-02 3.92.69.189:80 check' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
