#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
hour=0
minute=1
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    while [ $minute -lt 60 ]; do
	echo $minute
	let minute=$minute+1
    done
    let minute=1
    let hour=$hour+1
done
