#!/usr/bin/env bash
# Retrieves info on file "holbertonschool"
if [ -e "holbertonschool" ]
then
	echo "holbertonschool file exists"
	if [ -s "holbertonschool"]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f "holbertonschool" ]
	then
		echo "holbertonschool is regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
