#!/usr/bin/env bash
# Install Apache and fix an html page
sudo apt-get -y update
sudo apt-get -y install apache2
echo "ServerName localhost" >> sudo tee -a /etc/apache2/apache2.conf
echo "Hello Holberton"
service apache2 start
